Added options; code cleanup

diff --git a/fw b/fw
--- a/fw
+++ b/fw
@@ -8,35 +8,70 @@ sfo_script_name=sfo
 
 # Script starts here ##########################################################
 
+show_usage() {
+  echo "Usage: ${0##*/} [options] [file|directory ...]" >&2
+}
+
+show_help() {
+  show_usage 2>&1
+  echo "
+  Shows PS4 PKGs' SDK version. If it matches your PS4 firmware, the game or
+  patch might run without the need for a backport. DLC has no FW requirements.
+
+  If no files or directories are specified, the current directory will be used.
+
+  Options:
+    -h  Display this help info
+    -r  Traverse directories recursively"
+  exit
+}
+
+# Default options
+find_option="-maxdepth 1"
+
+# Parse command line options
+while [[ $1 == "-"?* ]]; do
+  for ((i=1;i<${#1};i++)); do
+    case ${1:$i:1} in
+      h) show_help ;;
+      r) find_option= ;;
+      *) show_usage; exit 1 ;;
+    esac
+  done
+  shift
+done
+
 # Use current directory if no arguments provided
 [[ $* == "" ]] && set -- .
 
 # Accepts a PKG file name and returns its firmware version
 show_firmware() {
-  firmware=$("$sfo_script_name" "$1" pubtoolinfo \
-    | grep -Po '(?<=sdk_ver=)[0-9]{4}' \
-    | sed -e 's/\(^..\)/\1\./' -e 's/^0//')
-  if [[ ${PIPESTATUS[0]} != 0 ]]; then
-    echo -e "ERROR\\t$1"
-  else
+  if firmware=$("$sfo_script_name" "$1" pubtoolinfo); then
+    if [[ $firmware =~ sdk_ver=([0-9][0-9])([0-9][0-9]) ]]; then
+      firmware=${BASH_REMATCH[1]#0}.${BASH_REMATCH[2]}
+    else
+      firmware=
+    fi
     echo -e "$firmware\\t${1##*/}"
+  else
+    echo -e "ERROR\\t$1"
   fi
 }
-
-declare -a pkgfiles
 
 # Collect list of PKG files
 for arg in "$@"; do
   if [[ -d "$arg" ]]; then
     while read -r file; do
       pkgfiles+=("$file")
-    done < <(find "$arg" -maxdepth 1 -type f -iname '*.pkg')
+    done < <(find "$arg" $find_option -type f -iname '*.pkg')
   elif [[ -f "$arg" ]]; then
     pkgfiles+=("$arg")
+  else
+    echo -e "ERROR:\\t File not found: $arg" >&2
   fi
 done
 
-# Run firmware check on list
+# Run firmware check on that list
 if [[ ${pkgfiles[*]} != "" ]]; then
   echo -e "FW:\\tFile name:"
   for file in "${pkgfiles[@]}"; do
